### ISSUE TITLE
Spec version update needed

### ISSUE THREAD

**Issue by Data-Nexus** [smith-phil/galasubgraph#12]
It looks like we need to rerun graph codegen since the deployed version still shows a spec of 0.0.5

After running codegen, deploy it with a new version to the studio, you can then replace the IPFS hash in the below URL to ensure it is properly built:

https://ipfs.io/ipfs/QmZXuuGexefbgNNtzjR11KEup3SCXeiiyHQncpsgMXeViB

At the bottom of the page we will want to see "specVersion: 0.0.4"

**Comment by smith-phil** [comment]
Sure, I've been busy with work so I'll get to it this evening.

**Comment by smith-phil** [comment]
New IPFS hash is here: https://ipfs.io/ipfs/QmbgMYDkJf5J27ffEzbJZA45uuYTnv2Upx47KQTSmmSAuB

I'll publish it when gas is low, probably June 19th. The problem was my graph-cli version was outdated and was automatically changing the spec to 0.0.5 when I ran `graph codegen`.

I'll close this issue when the new version is published and synced.

**Comment by smith-phil** [comment]
I've published version 1.04 to mainnet and it's now [syncing](https://thegraph.com/explorer/subgraph?id=3wsJ9wuLNB3v9adE9Nik593Cba4MwchBEtneXjpL6EPg&view=Overview). 

Thanks again @Data-Nexus, if I can help out with any of your projects let me know.

**Comment by Data-Nexus** [comment]
Perfect. Looks great on my end.
